debug: false

ranking-refresh-minutes: 5
ranking-size: 10

boss-stack-radius: 5

boss-nametag: '{display} §7x{stack}'

kill-stack-item:
  material: written_book
  display: '&4Kill-Stack +{level}'
  lore:
  - '&7Aplique este livro na'
  - '&7sua matadora e suba nível.'
  - ''
  - ' &8 ▪ &fComando: &f/matadora '
  - ''
  glow: true
