# Ativa logs de depuração detalhados no console.
debug: false

# Permissão admin (reload, additens): servershops.admin

# -- Cash Shop --
cash-shop:
  command: shop
  aliases: []
  currency: cash

# -- Coins Shop --
coins-shop:
  command: loja
  aliases: []
  currency: coins

# -- Menu de categorias --
categories-menu:
  cash:
    title: SHOP
    rows: 3
  coins:
    title: Loja
    rows: 5

# -- Aparência das categorias --
# Moeda: {value} {symbol} {symbol_color} {primary_color} {secondary_color} {currency}
# Outros: {amount} {discount} {purchase-hint} {right-click-hint} {name} {release-date}
ui:
  cash-shop:
    back-icon:
      texture: '7437346d8bda78d525d19f540a95e4e79daeda795cbc5a13256236312cf'
      display: '&eVoltar'
      lore:
      - '&7Clique para voltar.'
    
    locked-display: '&c{name}'
    locked-hidden-date: §k??/??/???? ??:??
    locked-lore:
    - ''
    - '&8 ▪ &fLibera em: &7{release-date} '
    - ''
    - '&8 ▾ &cItem ainda bloqueado. '
    - ''

    product-lore:
    - ''
    - '&8 ▪ &fCusto: {symbol_color}{symbol}{primary_color}{value} {currency} '
    - ''
    - '&6Opções de uso:'
    - '{purchase-hint}'
    - '{right-click-hint}'

    no-discount-tag: '&cNenhum'
    purchase-hint: '&fBotão esquerdo &8➟ &7Comprar'
    ask-quantity-hint: '&fBotão esquerdo &8➟ &7Comprar'
    already-owned-hint: '&cProduto já adquirido.'
    right-click-hint: '&fBotão direito &8➟ &7Preview'
  
  coins-shop:
    back-icon:
      texture: '7437346d8bda78d525d19f540a95e4e79daeda795cbc5a13256236312cf'
      display: '&eVoltar'
      lore:
      - '&7Clique para voltar.'

    
    locked-display: '&c{name}'
    locked-hidden-date: §k??/??/???? ??:??
    locked-lore:
    - ''
    - '&8 ▪ &fLibera em: &7{release-date} '
    - ''
    - '&8 ▾ &cItem ainda bloqueado. '
    - ''

    product-lore:
    - ''
    - '&8 ▪ &fCusto: {symbol_color}{symbol}{primary_color}{value} {currency} '
    - '&8 ▪ &fDesconto: {discount} '
    - ''
    - '&aOpções de uso:'
    - '{purchase-hint}'
    - '{right-click-hint}'

    no-discount-tag: '&cNenhum'
    purchase-hint: '&fBotão esquerdo &8➟ &7Comprar'
    ask-quantity-hint: '&fBotão esquerdo &8➟ &7Comprar'
    already-owned-hint: '&cProduto já adquirido.'
    right-click-hint: '&fBotão direito &8➟ &7Preview'
    
    # Cor do {item} quando o produto não tem display name.
    fallback-item-name-color: '&a'
